import "./globals.css";
import { ArweaveWalletKit } from "arweave-wallet-kit";
import { Toaster } from "@/components/ui/toaster";
import { GameProvider } from "@/context/GameContext";
import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ArweaveWalletKit
          config={{
            permissions: [
              "ACCESS_ADDRESS",
              "ACCESS_PUBLIC_KEY",
              "SIGN_TRANSACTION",
              "DISPATCH",
            ],
            ensurePermissions: true,
          }}
          theme={{
            displayTheme: "light",
          }}
        >
          <GameProvider>
            <Navbar />
            <main className="flex-1 overflow-hidden">{children}</main>
            <Toaster />
            <Footer />
          </GameProvider>
        </ArweaveWalletKit>
      </body>
    </html>
  );
}
